<?php

/*
 * Soluble Japha
 *
 * @link      https://github.com/belgattitude/soluble-japha
 * @copyright Copyright (c) 2013-2020 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-japha/blob/master/LICENSE.md
 */

namespace SolubleTest\Japha\Bridge;

use PHPUnit\Framework\Attributes\Test;
use Soluble\Japha\Interfaces\JavaObject;
use Soluble\Japha\Bridge\Driver\Pjb62\ObjectIterator;
use Soluble\Japha\Bridge\Adapter;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-04 at 16:47:42.
 */
class AdapterUsageCommonTest extends TestCase
{
    /**
     * @var string
     */
    protected $servlet_address;

    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        \SolubleTestFactories::startJavaBridgeServer();

        $this->servlet_address = \SolubleTestFactories::getJavaBridgeServerAddress();

        $this->adapter = new Adapter([
            'driver' => 'Pjb62',
            'servlet_address' => $this->servlet_address,
        ]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    #[Test]
    public function methodCall(): void
    {
        $ba = $this->adapter;

        $javaString = $ba->java('java.lang.String', 'A key is a key!');
        $index = $javaString->indexOf('key');

        $this->assertSame(2, $index);

        // Method overloading, use the `indexOf(String, $fromIndex)` method
        $index = $javaString->indexOf('key', $fromIndex = 8);
        $this->assertSame(11, $index);
    }

    #[Test]
    public function javaBigInt(): void
    {
        $ba = $this->adapter;
        $bigint1 = $ba->java('java.math.BigInteger', 10);
        $bigint2 = $ba->java('java.math.BigInteger', 1234567890);
        $this->assertInstanceOf(JavaObject::class, $bigint1);
        $this->assertInstanceOf(JavaObject::class, $bigint2);
        $bigint1 = $bigint1->add($bigint2);

        $this->assertSame('1234567900', (string) $bigint1);
        $this->assertSame(1234567900, $bigint1->intValue());
    }

    #[Test]
    public function operators(): void
    {
        $ba = $this->adapter;
        $bigint = $ba->java('java.math.BigInteger', 10);
        $a = $bigint->intValue() * 4;
        $this->assertSame(40, $a);

        $int = $ba->java('java.lang.Integer', 10);
        $a = $int->intValue() * 4.15;
        $this->assertEqualsWithDelta(41.5, $a, PHP_FLOAT_EPSILON);
    }

    #[Test]
    public function javaStringsEncodings(): void
    {
        $ba = $this->adapter;

        // ascii
        $string = $ba->java('java.lang.String', 'Am I the only one ?');
        $this->assertInstanceOf(JavaObject::class, $string);
        $this->assertSame('Am I the only one ?', $string);
        $this->assertNotSame('Am I the only one', $string);

        // unicode - utf8
        $string = $ba->java('java.lang.String', '保障球迷權益');
        $this->assertInstanceOf(JavaObject::class, $string);
        $this->assertSame('保障球迷權益', $string);
        $this->assertNotSame('保障球迷', $string);

        $string = $ba->java('java.lang.String', '保éà');
        $this->assertInstanceOf(JavaObject::class, $string);
        $this->assertSame('保éà', $string);
    }

    #[Test]
    public function javaHashMap(): void
    {
        $ba = $this->adapter;
        $hash = $ba->java('java.util.HashMap', ['my_key' => 'my_value']);

        $this->assertSame(1, $hash->size());

        $this->assertInstanceOf(JavaObject::class, $hash);
        $this->assertSame('my_value', $hash->get('my_key'));
        $hash->put('new_key', 'oooo');
        $this->assertSame('oooo', $hash->get('new_key'));
        $hash->put('new_key', 'pppp');
        $this->assertSame('pppp', $hash->get('new_key'));

        $this->assertSame(4, $hash->get('new_key')->length());

        $hash->put('key', $ba->java('java.lang.String', '保障球迷權益'));
        $this->assertSame('保障球迷權益', $hash->get('key'));
        $this->assertSame(6, $hash->get('key')->length());

        $hashMap = $ba->java('java.util.HashMap', [
            'year' => 2017,
            'message' => 'Hello world',
            'data' => [0.2, 3.2, 4, 18.12]
        ]);

        $hashMap->put('message', '你好，世界');
        $this->assertSame('你好，世界', $hashMap->get('message'));
        //echo $hashMap->get('year') + 1;
    }

    #[Test]
    public function arrayList(): void
    {
        $ba = $this->adapter;
        $arrayList = $ba->java('java.util.ArrayList');

        $arrayList->add('Hello');
        $arrayList->add('World');

        $array = $ba->values($arrayList->toArray());
        $this->assertSame(['Hello', 'World'], $array);
    }

    #[Test]
    public function javaHashMapArrayValues(): void
    {
        $ba = $this->adapter;
        $array = [
            'name' => 'John doe',
            'age' => 26
        ];
        $map = $ba->java('java.util.HashMap', $array);

        $values = $map->values()->toArray();

        $v = $ba->values($values);
        $this->assertSame(array_values($array), $v);
    }

    #[Test]
    public function javaReflectArray(): void
    {
        $ba = $this->adapter;
        $arrayClass = $ba->javaClass('java.lang.reflect.Array');

        $array = [
            'name' => 'John doe',
            'age' => 26
        ];
        $map = $ba->java('java.util.HashMap', $array);

        $values = $map->values()->toArray();

        $v = [];
        for ($i = 0; $i < $arrayClass->getLength($values); ++$i) {
            $v[$i] = (string) $values[$i];
        }
        
        $this->assertSame(array_values($array), $v);
    }

    #[Test]
    public function javaConstructorOverloading(): void
    {
        $ba = $this->adapter;
        $vec1 = $ba->java('java.util.Vector', $initialCapacity = 1, $capacityIncrement = 2);
        $this->assertSame('java.util.Vector', $ba->getDriver()->getClassName($vec1));
        $vec2 = $ba->java('java.util.Vector', [1, 2, 3]);
        $this->assertSame('java.util.Vector', $ba->getDriver()->getClassName($vec2));

        $mathContext = $ba->java('java.math.MathContext', $precision = 2);
        $bigint = $ba->java('java.math.BigInteger', 123456);
        $bigdec = $ba->java('java.math.BigDecimal', $bigint, $scale = 2, $mathContext);

        $this->assertSame(1200, $bigdec->floatValue());
    }

    #[Test]
    public function javaWithDouble(): void
    {
        $ba = $this->adapter;
        $double = 1.212009867e6;
        $bigdec = $ba->java('java.math.BigDecimal', $double);
        $this->assertSame((int) $double, $bigdec->intValue());
        $this->assertSame((string) $double, $bigdec->toString());

        // WARNING THOSE ones won't equals (floats are not treated equally between php and Java)
        $this->assertNotSame($double, $bigdec->floatValue());
    }

    #[Test]
    public function javaWithDoubleFromValueOf(): void
    {
        $ba = $this->adapter;
        $double = 1.212009867e6;
        $bigdec = $ba->javaClass('java.math.BigDecimal')->valueOf($double);
        $this->assertSame((int) $double, $bigdec->intValue());
        $this->assertSame((string) $double, $bigdec->toString());
    }

    #[Test]
    public function fileReader(): void
    {
        $ba = $this->adapter;
        $reader = $ba->java(
            'java.io.BufferedReader',
            $ba->java('java.io.FileReader', __FILE__)
        );

        $content = '';
        while (($line = $reader->readLine()) != null) {
            $content .= $line.PHP_EOL;
        }
        
        $this->assertStringContainsString('testFileReader', $content);
    }

    #[Test]
    public function foreach(): void
    {
        $ba = $this->adapter;

        $arr = [
            'key1' => 'first_value',
            'key2' => 'second_value',
            'key3' => ['cool', 'cool', 'cool']
        ];

        $hashMap = $ba->java('java.util.HashMap', $arr);

        $newArr = [];
        foreach ($hashMap as $key => $value) {
            $newArr[$key] = $ba->getDriver()->values($value);
        }
        
        $this->assertSame($arr, $newArr);
    }

    #[Test]
    public function iterator(): void
    {
        $ba = $this->adapter;

        $system = $ba->javaClass('java.lang.System');
        $properties = $system->getProperties();

        foreach ($properties as $key => $value) {
            $this->assertIsString($key);
            $this->assertInstanceOf(JavaObject::class, $value);

            if ($key === 'java.version') {
                $this->assertStringStartsWith('1', $value->__toString());
            }
        }

        $iterator = $properties->getIterator();
        $this->assertInstanceOf(ObjectIterator::class, $iterator);
        $this->assertInstanceOf('Iterator', $iterator);

        foreach ($iterator as $key => $value) {
            $this->assertIsString($key);
            $this->assertInstanceOf(JavaObject::class, $value);

            if ($key === 'java.version') {
                $this->assertStringStartsWith('1', $value->__toString());
            }
        }
    }
}
