<?php

/*
 * Soluble Japha
 *
 * @link      https://github.com/belgattitude/soluble-japha
 * @copyright Copyright (c) 2013-2020 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-japha/blob/master/LICENSE.md
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62;

use PHPUnit\Framework\Attributes\Test;
use Soluble\Japha\Bridge\Driver\Pjb62\ParserTag;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class ParserTagTest extends TestCase
{
    #[Test]
    public function parserTag(): void
    {
        $pt = new ParserTag();
        $this->assertSame([], $pt->strings);
        $this->assertSame(0, $pt->n);
    }
}
