<?php

/*
 * Soluble Japha
 *
 * @link      https://github.com/belgattitude/soluble-japha
 * @copyright Copyright (c) 2013-2020 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-japha/blob/master/LICENSE.md
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62;

use PHPUnit\Framework\Attributes\Test;
use Soluble\Japha\Bridge\Driver\Pjb62\ParserString;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class ParserStringTest extends TestCase
{
    #[Test]
    public function parserString(): void
    {
        $pe = new ParserString();
        $pe->string = '1234';
        $pe->off = 0;
        $pe->length = 20;
        $this->assertSame('1234', $pe->getString());
        $this->assertSame('1234', $pe->toString());

        $pe->off = 1;
        $pe->length = 2;

        $this->assertSame('23', $pe->getString());
        $this->assertSame('23', $pe->toString());
    }

    #[Test]
    public function parserStringUTF8(): void
    {
        $pe = new ParserString();
        $pe->string = '你好，世界';
        $pe->off = 0;
        $pe->length = 20;
        $this->assertSame('你好，世界', $pe->getString());
        $this->assertSame('你好，世界', $pe->toString());
    }
}
